import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import toast, { Toaster } from 'react-hot-toast';
import NavBar from '@/components/NavBar';
import clsx from 'clsx';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Harmony Posts',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-black text-white')}>
        <Toaster position="bottom-center" />
        <NavBar></NavBar>
        {children}
      </body>
    </html>
  )
}
